### ISSUE TITLE
Can't Find JSON File

### ISSUE THREAD

**Issue by dirkmont** [HitmanHimself/cp77research#9]
When trying import to Blender, the following error is generated- 

bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
bpy.context.space_data.recent_folders_active = 0
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
Traceback (most recent call last):
  File "C:\Users\mmcgo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\i_scene_cp77_gltf\__init__.py", line 63, in execute
    file = open(BasePath + ".Material.json",mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\3D Assets\\Wolvenkit\\Judy 1\\files\\Raw\\base\\characters\\main_npc\\judy\\h1_001_wa_c__judy_baraindance.Material.json'

location: <unknown location>:-1

**Comment by kainotoa** [comment]
When u export meshes from wolvenkit, you have an option to export withMaterials and u can select appropriate image extension for textures export along with it and the json file will be generated, default export doesn't. For image extension avoid using DDS and jpg, use png or tga otherwise textures will be broken

**Comment by dirkmont** [comment]
Hi,
I select export with material, select TGA format- the mesh and JSON file are generated but when opening the file in Blender 2.93 I get the error that Blender Can't find the JSON file, the path is not valid?

"file = open(BasePath + ".Material.json",mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'F:\3D Assets\Wolvenkit\Judy 1\files\Raw\base\characters\main_npc\judy\h1_001_wa_c__judy_baraindance.Material.json'"

'F:\3D Assets\Wolvenkit\Judy 1\files\Raw\base\characters\main_npc\judy\h1_001_wa_c__judy_baraindance.Material.json' 

should it not read

'F:\3D Assets\Wolvenkit\Judy 1\files\Raw\base\characters\main_npc\judy\h1_001_wa_c__judy_baraindance\Material.json'

The JSON file is contained in a subdirectory within

'F:\3D Assets\Wolvenkit\Judy 1\files\Raw\base\characters\main_npc\judy\h1_001_wa_c__judy_baraindance'

**Comment by kainotoa** [comment]
you also need to update your wolvenkit, download the latest one, the json files will no longer be created in a subfolder
https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/latest
also delete %appdata%/RedModding

**Comment by dirkmont** [comment]
Hi
Did that, cleared previous install, downloaded new one from link, deleted %appdata%/RedModding, set up new version and it won't launch- crashes straight to desktop when loading game archives

**Comment by kainotoa** [comment]
> Hi
> Did that, cleared previous install, downloaded new one from link, deleted %appdata%/RedModding, set up new version and it won't launch- crashes straight to desktop when loading game archives

- you set the game path properly?
- game is in program files?
- wkit is in program files?
- you have the game open at the same time

**Comment by dirkmont** [comment]
I don't get the option to set any paths- Wolvenkit opens, shows that it's trying to load Game Arhives (baically freezes) then closes. In the Task Manager it shows as 'Suspended' before closing

**Comment by kainotoa** [comment]
you can go into the settings, select your cyberpunk2077.exe and restart wkit, create a new project and try again?

**Comment by dirkmont** [comment]
I can't- I launch Wolvenkit, the splash screen opens, then the main panel but at this point Wolvenkit becomes unresponsive then closes immediately, I'm not given the chance to set the path the Cyberpunk2077.exe at all
![image](https://user-images.githubusercontent.com/89967338/132090581-f2d2526b-945e-431f-abc6-1d06346964c6.png)

**Comment by kainotoa** [comment]
are you using the portable version or the installer? also where is your wolvenkit located, program files or something?

**Comment by dirkmont** [comment]
Portable version and the zip was extracted to this path-

F:\Downloads\WolvenKit-2201-0-8-2-1624961563\win-x64\WolvenKit.exe
